package com.zhanghuagui.uninstallapp.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zhanghuagui.uninstallapp.db.WhiteItem;

import com.zhanghuagui.uninstallapp.db.WhiteItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig whiteItemDaoConfig;

    private final WhiteItemDao whiteItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        whiteItemDaoConfig = daoConfigMap.get(WhiteItemDao.class).clone();
        whiteItemDaoConfig.initIdentityScope(type);

        whiteItemDao = new WhiteItemDao(whiteItemDaoConfig, this);

        registerDao(WhiteItem.class, whiteItemDao);
    }
    
    public void clear() {
        whiteItemDaoConfig.clearIdentityScope();
    }

    public WhiteItemDao getWhiteItemDao() {
        return whiteItemDao;
    }

}
